name: AKS CI/CD Deploy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write
  actions: write
  deployments: write

jobs:
  validate-and-whatif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Azure CLI
        uses: azure/cli@v1
        with:
          upgrade: true

      - name: Install Bicep CLI
        run: |
          az bicep install --version latest

      - name: Bicep build
        run: |
          az bicep build --file main.bicep

      - name: Bicep lint
        run: |
          az bicep lint --file main.bicep

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Resource group check
        id: rg
        run: |
          rg_exists=$(az group exists --name ${{ secrets.AKS_RG }} )
          echo "rg_exists=$rg_exists" >> $GITHUB_OUTPUT

      - name: What-If
        if: steps.rg.outputs.rg_exists == 'true'
        run: |
          if [ -f parameters.bicepparam ]; then
            PARAMETERS='@parameters.bicepparam'
          else
            PARAMETERS='@parameters.json'
          fi
          az deployment group what-if --resource-group ${{ secrets.AKS_RG }} --template-file main.bicep --parameters $PARAMETERS --no-prompt

      - name: Validate (will create RG if missing)
        if: steps.rg.outputs.rg_exists != 'true'
        run: |
          az group create --name ${{ secrets.AKS_RG }} --location ${{ secrets.AKS_LOCATION }}
          if [ -f parameters.bicepparam ]; then
            PARAMETERS='@parameters.bicepparam'
          else
            PARAMETERS='@parameters.json'
          fi
          az deployment group validate --resource-group ${{ secrets.AKS_RG }} --template-file main.bicep --parameters $PARAMETERS

  deploy-on-merge:
    needs: validate-and-whatif
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy AKS
        run: |
          if [ -f parameters.bicepparam ]; then
            PARAMETERS='@parameters.bicepparam'
          else
            PARAMETERS='@parameters.json'
          fi
          az deployment group create --resource-group ${{ secrets.AKS_RG }} --template-file main.bicep --parameters $PARAMETERS --confirm-with-what-if
